In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Tất cả thư viện hoạt động!")

Tất cả thư viện hoạt động!

In [2]:
# --- BƯỚC 1: Đọc file ---
df = pd.read_csv('Superstore.csv', encoding='latin-1')

print("="*50)
print("TỔNG QUAN DATASET")
print("="*50)
print(f"Số dòng (rows):      {df.shape[0]}")
print(f"Số cột (columns):    {df.shape[1]}")

print("\n" + "="*50)
print("KIỂU DỮ LIỆU TỪNG CỘT")
print("="*50)
print(df.dtypes)

print("\n" + "="*50)
print("5 DÒNG ĐẦU TIÊN")
print("="*50)
df.head()

==================================================
TỔNG QUAN DATASET
==================================================
Số dòng (rows):      9994
Số cột (columns):    21

==================================================
KIỂU DỮ LIỆU TỪNG CỘT
==================================================
Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

==================================================
5 DÒNG ĐẦU TIÊN
==================================================

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2013-138688,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [3]:
# --- BƯỚC 2: Kiểm tra dữ liệu thiếu và trùng lặp ---
print("GIÁ TRỊ THIẾU (NULL) TRONG MỖI CỘT:")
print(df.isnull().sum())
print(f"\nTổng giá trị null: {df.isnull().sum().sum()}")

print("\n" + "="*50)
print(f"Số dòng trùng lặp: {df.duplicated().sum()}")

GIÁ TRỊ THIẾU (NULL) TRONG MỖI CỘT:
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

Tổng giá trị null: 0

==================================================
Số dòng trùng lặp: 0

In [4]:
# --- BƯỚC 3: Chuyển đổi kiểu dữ liệu phù hợp ---

# Postal Code nên là string (không phải số)
df['Postal Code'] = df['Postal Code'].astype(str)

# Chuyển cột ngày sang datetime
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d-%m-%Y')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%d-%m-%Y')

print("Kiểu dữ liệu SAU khi chuyển đổi:")
print(df.dtypes)

print("\nKích thước dataframe:", df.shape)
print("\n5 dòng đầu tiên:")
df.head()

Kiểu dữ liệu SAU khi chuyển đổi:
Row ID                    int64
Order ID                    str
Order Date       datetime64[us]
Ship Date        datetime64[us]
Ship Mode                   str
Customer ID                 str
Customer Name               str
Segment                     str
Country                     str
City                        str
State                       str
Postal Code                 str
Region                      str
Product ID                  str
Category                    str
Sub-Category                str
Product Name                str
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

Kích thước dataframe: (9994, 21)

5 dòng đầu tiên:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2013-152156,2013-11-09,2013-11-12,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2013-138688,2013-06-13,2013-06-17,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2012-108966,2012-10-11,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2012-108966,2012-10-11,2012-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [5]:
# --- BƯỚC 4: Lưu dữ liệu đã clean ---
df.to_csv('dataCleand.csv', index=False, encoding='utf-8-sig')
print("Đã lưu file dataCleand.csv thành công!")
print(f"Số dòng: {df.shape[0]}, Số cột: {df.shape[1]}")

Đã lưu file dataCleand.csv thành công!
Số dòng: 9994, Số cột: 21